# Dirvana configuration file
# Documentation: https://github.com/NikitaCOEUR/dirvana
conditions:
  no_kubeconfig: &no_kubeconfig
    when:
      all:
        - var: PROJECT_NAME # Test if ENV var PROJECT_NAME is set as example
        - command: kubectl  # Test if command kubectl is available

# Shell aliases
aliases:
  g:
    command: git
    completion: git
  gs: git status
  gd: git diff
  gov: govc

  kubecolor: &kubecolor
    command: kubecolor
    completion: kubectl
    <<: *no_kubeconfig

  k: *kubecolor

  kubectl:
    command: kubectl
    <<: *no_kubeconfig

  h: helm
  p: packer
  t: task
  tf: terraform



# Shell functions
functions:
  mkcd: |
    mkdir -p "$1" && cd "$1"
  greet: |
    echo "Hello, $1!"

# Environment variables
env:
  PROJECT_NAME: dirvana
  GIT_BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  BUILD_DIR:
    sh: pwd
  TEST_OVERRIDED_VAR: from-root

# Set to true to ignore parent configs
local_only: false
