// Package shell generates shell code from Dirvana configuration.
package shell

import (
	"fmt"
	"maps"
	"slices"
	"strings"

	"github.com/NikitaCOEUR/dirvana/internal/config"
)

// Generator generates shell code from configuration
type Generator struct {
	Shell string // Target shell: "bash", "zsh", or "" for both
}

// NewGenerator creates a new shell code generator
func NewGenerator() *Generator {
	return &Generator{
		Shell: "", // Generate for both shells by default
	}
}

// WithShell sets the target shell
func (g *Generator) WithShell(shell string) *Generator {
	g.Shell = shell
	return g
}

// Generate creates shell code for aliases, functions, and environment variables.
// completionMap maps alias names to their completion commands (from buildCompletionMap).
// staticEnv contains simple string values, shellEnv contains shell commands to execute.
func (g *Generator) Generate(aliases map[string]config.AliasConfig, functions, staticEnv, shellEnv, completionMap map[string]string) string {
	// Generate lightweight wrappers using dirvana exec
	return g.generateWithWrappers(aliases, functions, staticEnv, shellEnv, completionMap)
}

// escapeValue escapes single quotes in values
func escapeValue(s string) string {
	return strings.ReplaceAll(s, "'", "'\\''")
}

// indent adds indentation to multiline strings
func indent(s string) string {
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = "  " + line
		}
	}
	return strings.Join(lines, "\n")
}

// sortedKeys returns sorted keys from a map for deterministic output
func sortedKeys[V any](m map[string]V) []string {
	return slices.Sorted(maps.Keys(m))
}

// generateAliases generates shell-specific alias/function wrappers and returns
// the generated lines along with a map of alias->underlying command for completion registration.
// completionMap is the source of truth for completion commands (from buildCompletionMap in helpers.go).
func (g *Generator) generateAliases(aliases map[string]config.AliasConfig, completionMap map[string]string) ([]string, map[string]string) {
	var parts []string
	aliasCommands := make(map[string]string)
	keys := sortedKeys(aliases)

	// For zsh and fish, we need to use functions instead of aliases for completion to work
	// For bash, aliases work fine
	useShellFunctions := (g.Shell == Zsh || g.Shell == Fish)

	if useShellFunctions {
		parts = append(parts, "\n# Aliases (using dirvana exec wrapper as functions)")
		for _, key := range keys {
			if g.Shell == Fish {
				// Fish uses a different function syntax
				parts = append(parts, fmt.Sprintf("function %s; dirvana exec %s $argv; end", key, key))
			} else {
				// Clean up any existing completion before defining function
				// This prevents completion conflicts when reusing alias names
				parts = append(parts, fmt.Sprintf("complete -r %s 2>/dev/null || true", key))
				parts = append(parts, fmt.Sprintf("%s() { dirvana exec %s \"$@\"; }", key, key))
			}
			if cmd, ok := completionMap[key]; ok {
				aliasCommands[key] = baseCommand(cmd)
			}
		}
	} else {
		parts = append(parts, "\n# Aliases (using dirvana exec wrapper)")
		for _, key := range keys {
			// Clean up any existing completion before defining alias
			// This prevents completion conflicts when reusing alias names
			parts = append(parts, fmt.Sprintf("complete -r %s 2>/dev/null || true", key))
			parts = append(parts, fmt.Sprintf("alias %s='dirvana exec %s'", key, key))
			if cmd, ok := completionMap[key]; ok {
				aliasCommands[key] = baseCommand(cmd)
			}
		}
	}

	return parts, aliasCommands
}

// baseCommand extracts the first word from a command string (e.g., "git status" -> "git").
func baseCommand(cmd string) string {
	if parts := strings.Fields(cmd); len(parts) > 0 {
		return parts[0]
	}
	return cmd
}

// generateWithWrappers generates minimal shell code using dirvana exec wrappers
// This is much faster than the old approach as it doesn't generate complex completion logic
func (g *Generator) generateWithWrappers(aliases map[string]config.AliasConfig, functions, staticEnv, shellEnv, completionMap map[string]string) string {
	var parts []string

	parts = append(parts, "# Generated by Dirvana - Do not edit manually")
	parts = append(parts, "# Using wrapper architecture for better performance")

	// Collect alias->underlying command mapping for completion registration
	aliasCommands := make(map[string]string)

	// Generate simple alias/function wrappers
	if len(aliases) > 0 {
		aliasParts, cmds := g.generateAliases(aliases, completionMap)
		parts = append(parts, aliasParts...)
		for k, v := range cmds {
			aliasCommands[k] = v
		}
	}

	// Generate real shell functions
	// Functions contain actual shell code and must be defined directly (not via dirvana exec)
	if len(functions) > 0 {
		parts = append(parts, "\n# Functions")
		keys := sortedKeys(functions)
		for _, key := range keys {
			body := functions[key]
			if g.Shell == Fish {
				// Fish syntax: function name; ...; end
				parts = append(parts, fmt.Sprintf("function %s\n%s\nend", key, indent(body)))
			} else {
				// Bash/Zsh syntax: name() { ...; }
				parts = append(parts, fmt.Sprintf("%s() {\n%s\n}", key, indent(body)))
			}
			// Functions have no underlying command
			aliasCommands[key] = ""
		}
	}

	// Generate static environment variables
	if len(staticEnv) > 0 {
		parts = append(parts, "\n# Environment Variables")
		keys := sortedKeys(staticEnv)
		for _, key := range keys {
			value := staticEnv[key]
			if g.Shell == Fish {
				// Fish syntax: set -gx VAR value
				parts = append(parts, fmt.Sprintf("set -gx %s '%s'", key, escapeValue(value)))
			} else {
				// Bash/Zsh syntax: export VAR=value
				parts = append(parts, fmt.Sprintf("export %s='%s'", key, escapeValue(value)))
			}
		}
	}

	// Generate dynamic environment variables (shell commands that get executed)
	if len(shellEnv) > 0 {
		parts = append(parts, "\n# Dynamic Environment Variables")
		keys := sortedKeys(shellEnv)
		for _, key := range keys {
			shellCmd := shellEnv[key]
			if g.Shell == Fish {
				// Fish syntax: set -gx VAR (command)
				parts = append(parts, fmt.Sprintf("set -gx %s (%s)", key, shellCmd))
			} else {
				// Bash/Zsh syntax: export VAR="$(command)"
				parts = append(parts, fmt.Sprintf("export %s=\"$(%s)\"", key, shellCmd))
			}
		}
	}

	// Generate smart completion function for bash, zsh, and fish
	if len(aliasCommands) > 0 {
		parts = append(parts, "\n# Completions (via dirvana completion)")
		completionGen := NewCompletionGenerator(g.Shell)
		parts = append(parts, completionGen.GenerateCompletionFunction(aliasCommands)...)
	}

	return strings.Join(parts, "\n") + "\n"
}
